#!/bin/bash
DBEXISTS=/var/lib/pgsql/data/pg_hba.conf
POSTMASTER=/var/lib/pgsql/data/postmaster.pid
#############################################
# Check if database exists if not create it
#############################################
if test -f "$DBEXISTS"; then
	echo "Postgres database exists"
else
	echo "Postgres database setup"
  	/usr/bin/initdb --pgdata=/var/lib/pgsql/data -E 'UTF-8' --lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8'
  if test -f "$DBEXISTS"; then
	  echo "host all  all    0.0.0.0/0  md5" >> /var/lib/pgsql/data/pg_hba.conf
	  echo "listen_addresses='*'" >> /var/lib/pgsql/data/postgresql.conf
  fi
	/usr/bin/pg_ctl start -D /var/lib/pgsql/data -l /var/lib/pgsql/serverlog
	/scripts/createdb
fi
############################################
# Start database if not running
############################################
CMD=`pgrep -fa -- -D |grep postgres |wc -l`
if [ $(("$CMD")) -eq 0 ]
then
	echo "Starting Postgres"
	if test -f "$POSTMASTER"; then
		rm /var/lib/pgsql/data/postmaster.pid
	fi
	/usr/bin/pg_ctl start -D /var/lib/pgsql/data -l /var/lib/pgsql/serverlog
else
	echo "Postgres already running..."
fi
############################################################
# This to prevent docker from stopping running container.
############################################################
while true
do
  sleep 100
done
